apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-privileged
rules:
- apiGroups:
  - policy
  resourceNames:
  - vmware-system-privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-privileged-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: nginx-headers
